### ISSUE TITLE
[BUG] Dieses Auth-Plugin ist in der Konfiguration nicht aktiviert, Sie sollten es deaktivieren.

### ISSUE THREAD

**Issue by LMS235** [cosmocode/dokuwiki-plugin-oauthazure#1]
Im Wiki ist oauth mit oauthazure aktiv, jedoch wird im Erweiterungsmanager weiterhin "Dieses Auth-Plugin ist in der Konfiguration nicht aktiviert, Sie sollten es deaktivieren." angezeigt.

Übrigens wird auch unter dem Plain Auth Plugin das gleiche angezeigt, obwohl die "lokale" Anmeldung im oauth NICHT deaktiviert wurde.

![image](https://user-images.githubusercontent.com/8693550/196458798-e032ee61-5844-4e97-8da6-4e41f3b1a1e6.png)
--> oauth, damit ja auch azureouth aktiviert (funktioniert auch)

![image](https://user-images.githubusercontent.com/8693550/196458988-013b9006-aa76-4bf9-87dd-cce314f66ce0.png)
--> damit ist eben Plain Auth immer noch aktiv

Die Meldungen verwirren hier

**Comment by splitbrain** [comment]
The oauth sub plugins were marked wrongly as auth plugins. Fixed.
