### ISSUE TITLE
Cleaning up "cache" folder go to 'Disconnect' MS-Online page instead of logon

### ISSUE THREAD

**Issue by eduardomozart** [cosmocode/dokuwiki-plugin-oauthazure#5]
### Issue Description

When manually removing the contents from "cache" folder, it redirects the user to the MS Online "Disconnect" page instead of the login page of DokuWiki.

**Comment by splitbrain** [comment]
Please add more details here. Especially on the timing of what happens when.

**Comment by eduardomozart** [comment]
I was unable to reproduce the bug. Closing.
